# HW_1

## a_tensor_initalization.py

In [3]:
import torch

# [핵심코드] torch.Tensor 클래스 사용 예시
t1 = torch.Tensor([1, 2, 3], device='cpu')  # [핵심코드] CPU에서 1차원 텐서를 생성
print(t1.dtype)   # >>> torch.float32
print(t1.device)  # >>> cpu
print(t1.requires_grad)  # >>> False
print(t1.size())  # [핵심코드] 텐서의 크기 확인, torch.Size([3])
print(t1.shape)   # [핵심코드] 텐서의 형태 확인, torch.Size([3])

# [핵심코드] GPU 장치를 사용할 경우
# t1_cuda = t1.to(torch.device('cuda'))
# 또는 간단한 방법으로
# t1_cuda = t1.cuda()
t1_cpu = t1.cpu()  # [핵심코드] CPU로 텐서를 이동

print("#" * 50, 1)

# [핵심코드] torch.tensor 함수 사용 예시
t2 = torch.tensor([1, 2, 3], device='cpu')  # [핵심코드] CPU에서 정수형 텐서를 생성
print(t2.dtype)  # >>> torch.int64
print(t2.device)  # >>> cpu
print(t2.requires_grad)  # >>> False
print(t2.size())  # [핵심코드] 텐서의 크기 확인, torch.Size([3])
print(t2.shape)  # [핵심코드] 텐서의 형태 확인, torch.Size([3])

# [핵심코드] GPU 장치를 사용할 경우
# t2_cuda = t2.to(torch.device('cuda'))
# 또는 간단한 방법으로
# t2_cuda = t2.cuda()
t2_cpu = t2.cpu()  # [핵심코드] CPU로 텐서를 이동

print("#" * 50, 2)

# [핵심코드] 다양한 형태의 텐서 생성 및 차원 확인
a1 = torch.tensor(1)  # [핵심코드] 0차원 텐서
print(a1.shape, a1.ndim)

a2 = torch.tensor([1])  # [핵심코드] 1차원 텐서
print(a2.shape, a2.ndim)

a3 = torch.tensor([1, 2, 3, 4, 5])  # [핵심코드] 1차원 텐서
print(a3.shape, a3.ndim)

a4 = torch.tensor([[1], [2], [3], [4], [5]])  # [핵심코드] 2차원 텐서
print(a4.shape, a4.ndim)

a5 = torch.tensor([  # [핵심코드] 2차원 텐서
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim)

a6 = torch.tensor([  # [핵심코드] 3차원 텐서
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print(a6.shape, a6.ndim)

a7 = torch.tensor([  # [핵심코드] 4차원 텐서
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim)

a8 = torch.tensor([  # [핵심코드] 4차원 텐서, 각 요소가 2차원 배열인 경우
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim)

a9 = torch.tensor([  # [핵심코드] 5차원 텐서
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim)

a10 = torch.tensor([  # [핵심코드] 2차원 텐서
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print(a10.shape, a10.ndim)

a10 = torch.tensor([  # [핵심코드] 3차원 텐서
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
])
print(a10.shape, a10.ndim)

# 기술적 사항
# 1. torch.Tensor와 torch.tensor의 차이를 이해할 수 있다. 전자는 기본 텐서 생성, 후자는 데이터 타입 지정이 가능하다.
# 2. 다양한 차원의 텐서를 생성하고 각 텐서의 차원(ndim)과 형태(shape)를 확인하는 방법을 익혔다.
# 3. CUDA를 활용하여 GPU에서 텐서를 다루는 방법을 설명하였다.

# 고찰
# 1. 텐서의 차원과 형태를 이해하는 것은 딥러닝 모델을 구성하는 데 매우 중요하다. 각 차원은 데이터의 구조를 나타내며, 올바른 차원으로 모델을 설계해야 한다.
# 2. CPU와 GPU 간의 텐서 이동은 성능 최적화를 위해 필수적이다. 대규모 데이터 처리 시 GPU를 활용해야 하므로 이를 고려해야 한다.


torch.float32
cpu
False
torch.Size([3])
torch.Size([3])
################################################## 1
torch.int64
cpu
False
torch.Size([3])
torch.Size([3])
################################################## 2
torch.Size([]) 0
torch.Size([1]) 1
torch.Size([5]) 1
torch.Size([5, 1]) 2
torch.Size([3, 2]) 2
torch.Size([3, 2, 1]) 3
torch.Size([3, 1, 2, 1]) 4
torch.Size([3, 1, 2, 3]) 4
torch.Size([3, 1, 2, 3, 1]) 5
torch.Size([4, 5]) 2
torch.Size([4, 1, 5]) 3


In [5]:
# 잘못된 텐서 생성 예시
a11 = torch.tensor([  # [핵심코드] 4차원 텐서 생성 시 오류 발생
    [[[1, 2, 3], [4, 5]]],  # 이 부분에서 오류 발생, 각 내부 리스트의 길이가 불일치
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
])

ValueError: expected sequence of length 3 at dim 3 (got 2)

## b_tensor_initalization_copy.py

In [8]:
import torch
import numpy as np

# [핵심코드] 리스트를 텐서로 변환하는 방법
l1 = [1, 2, 3]
t1 = torch.Tensor(l1)  # [핵심코드] 기본 텐서 생성

l2 = [1, 2, 3]
t2 = torch.tensor(l2)  # [핵심코드] 데이터 타입이 자동으로 설정되는 텐서 생성

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3)  # [핵심코드] 기존 데이터를 참조하는 텐서 생성

# 리스트의 첫 번째 요소를 변경
l1[0] = 100
l2[0] = 100
l3[0] = 100

# 각 텐서 출력
print(t1)  # [핵심코드] t1은 l1의 복사본으로, l1의 변경이 반영되지 않음
print(t2)  # [핵심코드] t2는 l2의 복사본으로, l2의 변경이 반영되지 않음
print(t3)  # [핵심코드] t3은 l3의 참조로, l3의 변경이 반영됨

print("#" * 100)

# [핵심코드] Numpy 배열을 텐서로 변환하는 방법
l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)  # [핵심코드] Numpy 배열을 복사하여 텐서 생성

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)  # [핵심코드] Numpy 배열을 복사하여 텐서 생성

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)  # [핵심코드] Numpy 배열을 참조하는 텐서 생성

# Numpy 배열의 첫 번째 요소를 변경
l4[0] = 100
l5[0] = 100
l6[0] = 100

# 각 텐서 출력
print(t4)  # [핵심코드] t4는 l4의 복사본으로, l4의 변경이 반영되지 않음
print(t5)  # [핵심코드] t5는 l5의 복사본으로, l5의 변경이 반영되지 않음
print(t6)  # [핵심코드] t6은 l6의 참조로, l6의 변경이 반영됨

# 기술적 사항
# 1. torch.Tensor와 torch.tensor는 데이터를 복사하여 새로운 텐서를 생성하며, torch.as_tensor는 기존 데이터를 참조하여 텐서를 생성한다.
# 2. 리스트나 Numpy 배열의 요소를 변경할 때, 텐서의 내용이 어떻게 반영되는지를 이해할 수 있다.

# 고찰
# 1. 데이터의 복사 여부에 따라 텐서의 변경 사항이 달라지므로, 메모리 사용 및 성능 최적화 측면에서 상황에 맞는 함수 선택이 중요하다.
# 2. Numpy 배열과 PyTorch 텐서 간의 상호작용을 이해하는 것은 데이터 전처리 및 모델 학습 과정에서 매우 중요하다.


tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
####################################################################################################
tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([100,   2,   3], dtype=torch.int32)


## c_tensor_initalization_constant_values.py

In [11]:
import torch

# [핵심코드] 텐서를 생성하는 다양한 방법: 모든 요소가 1인 텐서
t1 = torch.ones(size=(5,))  # [핵심코드] 크기가 5인 1로 채워진 텐서 생성
t1_like = torch.ones_like(input=t1)  # [핵심코드] t1과 같은 크기의 1로 채워진 텐서 생성
print(t1)  # >>> tensor([1., 1., 1., 1., 1.])
print(t1_like)  # >>> tensor([1., 1., 1., 1., 1.])

# [핵심코드] 텐서를 생성하는 다양한 방법: 모든 요소가 0인 텐서
t2 = torch.zeros(size=(6,))  # [핵심코드] 크기가 6인 0으로 채워진 텐서 생성
t2_like = torch.zeros_like(input=t2)  # [핵심코드] t2와 같은 크기의 0으로 채워진 텐서 생성
print(t2)  # >>> tensor([0., 0., 0., 0., 0., 0.])
print(t2_like)  # >>> tensor([0., 0., 0., 0., 0., 0.])

# [핵심코드] 텐서를 생성하는 방법: 비어 있는 텐서
t3 = torch.empty(size=(4,))  # [핵심코드] 크기가 4인 비어 있는 텐서 생성
t3_like = torch.empty_like(input=t3)  # [핵심코드] t3와 같은 크기의 비어 있는 텐서 생성
print(t3)  # >>> tensor([0., 0., 0., 0.]) (초기값은 정해져 있지 않음)
print(t3_like)  # >>> tensor([0., 0., 0., 0.]) (초기값은 정해져 있지 않음)

# [핵심코드] 단위 행렬 생성
t4 = torch.eye(n=3)  # [핵심코드] 3x3 단위 행렬 생성
print(t4)

# 기술적 사항
# 1. torch.ones, torch.zeros, torch.empty, torch.eye와 같은 함수를 사용하여 다양한 형태의 텐서를 쉽게 생성할 수 있다.
# 2. ones_like 및 zeros_like 함수는 기존 텐서와 같은 크기의 텐서를 생성하는 데 유용하다.

# 고찰
# 1. 텐서의 초기화 방식에 따라 메모리 효율성을 고려할 수 있으며, 필요한 경우에 맞는 초기화 방법을 선택해야 한다.
# 2. 단위 행렬은 선형 대수에서 매우 중요한 역할을 하며, 텐서 연산에서 자주 사용되므로 이를 이해하는 것이 중요하다.


tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([2.3694e-38, 1.4013e-45, 0.0000e+00, 0.0000e+00])
tensor([7.0065e-45, 0.0000e+00, 0.0000e+00, 0.0000e+00])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


## d_tensor_initalization_random_value.py

In [14]:
import torch

# [핵심코드] 정수로 구성된 랜덤 텐서 생성
t1 = torch.randint(low=10, high=20, size=(1, 2))  # [핵심코드] 10 이상 20 미만의 정수를 랜덤으로 생성
print(t1)

# [핵심코드] 균일 분포에서 샘플링한 랜덤 텐서 생성
t2 = torch.rand(size=(1, 3))  # [핵심코드] 0과 1 사이의 랜덤 실수 생성
print(t2)

# [핵심코드] 정규 분포에서 샘플링한 랜덤 텐서 생성
t3 = torch.randn(size=(1, 3))  # [핵심코드] 평균 0, 표준편차 1의 정규 분포에서 랜덤 실수 생성
print(t3)

# [핵심코드] 정규 분포에 따라 랜덤 텐서 생성
t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2))  # [핵심코드] 평균 10, 표준편차 1인 정규 분포에서 샘플링
print(t4)

# [핵심코드] 균일 간격의 텐서 생성
t5 = torch.linspace(start=0.0, end=5.0, steps=3)  # [핵심코드] 0과 5 사이를 3개의 균일한 간격으로 나눈 텐서 생성
print(t5)

# [핵심코드] 일정 간격의 정수 텐서 생성
t6 = torch.arange(5)  # [핵심코드] 0부터 4까지의 정수로 구성된 텐서 생성
print(t6)

print("#" * 30)

# [핵심코드] 랜덤 텐서의 시드 설정
torch.manual_seed(1729)  # [핵심코드] 랜덤 시드를 설정하여 재현 가능성 확보
random1 = torch.rand(2, 3)  # [핵심코드] 2x3 크기의 랜덤 텐서 생성
print(random1)

random2 = torch.rand(2, 3)  # [핵심코드] 또 다른 2x3 크기의 랜덤 텐서 생성
print(random2)

print()

# [핵심코드] 동일한 시드로 랜덤 텐서 생성
torch.manual_seed(1729)  # [핵심코드] 동일한 시드를 설정하여 동일한 랜덤 값을 생성
random3 = torch.rand(2, 3)  # [핵심코드] 2x3 크기의 랜덤 텐서 생성
print(random3)

random4 = torch.rand(2, 3)  # [핵심코드] 또 다른 2x3 크기의 랜덤 텐서 생성
print(random4)

# 기술적 사항
# 1. 다양한 방법으로 랜덤 텐서를 생성할 수 있으며, 각 방법은 서로 다른 분포에서 샘플링한다.
# 2. torch.manual_seed를 사용하여 랜덤 텐서 생성의 재현성을 확보할 수 있다.

# 고찰
# 1. 랜덤 텐서 생성은 딥러닝 모델에서 데이터 샘플링, 초기화 등에 많이 사용되므로 이해하고 활용하는 것이 중요하다.
# 2. 랜덤 시드를 설정하는 것은 실험의 재현성을 보장하기 위해 필수적이며, 이를 통해 결과를 비교할 수 있다.


tensor([[19, 14]])
tensor([[0.9280, 0.1564, 0.2245]])
tensor([[-0.1218,  0.6751,  1.9434]])
tensor([[ 9.1712, 10.5786],
        [ 9.0025, 11.8824],
        [ 9.6794,  9.6363]])
tensor([0.0000, 2.5000, 5.0000])
tensor([0, 1, 2, 3, 4])
##############################
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


## e_tensor_type_conversion.py

In [17]:
import torch

# [핵심코드] 기본 텐서 생성 및 데이터 타입 확인
a = torch.ones((2, 3))  # [핵심코드] 크기 (2, 3)인 1로 채워진 텐서 생성
print(a.dtype)  # [핵심코드] 기본 데이터 타입은 float32

# [핵심코드] 특정 데이터 타입을 가진 텐서 생성
b = torch.ones((2, 3), dtype=torch.int16)  # [핵심코드] int16 타입의 1로 채워진 텐서 생성
print(b)

# [핵심코드] 랜덤 텐서 생성 후 스케일링
c = torch.rand((2, 3), dtype=torch.float64) * 20.  # [핵심코드] float64 타입으로 0~20 사이의 랜덤 텐서 생성
print(c)

# [핵심코드] 데이터 타입 변환
d = b.to(torch.int32)  # [핵심코드] int16 타입의 텐서를 int32로 변환
print(d)

# [핵심코드] double과 short 타입의 텐서 생성
double_d = torch.ones(10, 2, dtype=torch.double)  # [핵심코드] double 타입의 10x2 텐서 생성
short_e = torch.tensor([[1, 2]], dtype=torch.short)  # [핵심코드] short 타입의 1x2 텐서 생성

# [핵심코드] 제로 텐서를 생성한 후 타입 설정
double_d = torch.zeros(10, 2).double()  # [핵심코드] 10x2 크기의 제로 텐서를 double 타입으로 변환
short_e = torch.ones(10, 2).short()  # [핵심코드] 10x2 크기의 1로 채워진 텐서를 short 타입으로 생성

# [핵심코드] 데이터 타입 출력
double_d = torch.zeros(10, 2).to(torch.double)  # [핵심코드] double 타입의 제로 텐서 생성
short_e = torch.ones(10, 2).to(dtype=torch.short)  # [핵심코드] short 타입의 1로 채워진 텐서 생성

print(double_d.dtype)  # [핵심코드] double 타입 확인
print(short_e.dtype)  # [핵심코드] short 타입 확인

# [핵심코드] 랜덤 double 텐서 생성 및 타입 변환
double_f = torch.rand(5, dtype=torch.double)  # [핵심코드] double 타입의 랜덤 텐서 생성
short_g = double_f.to(torch.short)  # [핵심코드] double 텐서를 short 타입으로 변환
print((double_f * short_g).dtype)  # [핵심코드] 두 텐서의 곱의 데이터 타입 출력

# 기술적 사항
# 1. 텐서 생성 시 데이터 타입을 지정할 수 있으며, 다양한 타입 간 변환이 가능하다.
# 2. torch.ones, torch.zeros, torch.rand와 같은 함수는 데이터 타입을 설정할 수 있는 다양한 옵션을 제공한다.

# 고찰
# 1. 데이터 타입은 메모리 사용과 연산 속도에 큰 영향을 미치므로, 적절한 타입 선택이 중요하다.
# 2. 다양한 데이터 타입 간의 변환을 이해하는 것은 텐서 연산에서의 유연성을 높여준다.


torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[18.0429,  7.2532, 19.6519],
        [10.8626,  2.1505, 19.6913]], dtype=torch.float64)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
torch.float64
torch.int16
torch.float64


## f_tensor_operations.py

In [20]:
import torch

# 텐서 생성 및 덧셈 연산
t1 = torch.ones(size=(2, 3))  # 크기 (2, 3)인 1로 채워진 텐서 생성
t2 = torch.ones(size=(2, 3))  # 또 다른 크기 (2, 3)인 1로 채워진 텐서 생성
t3 = torch.add(t1, t2)  # torch.add를 사용한 덧셈
t4 = t1 + t2  # 연산자 오버로딩을 통한 덧셈
print(t3)  # 덧셈 결과 출력
print(t4)  # 덧셈 결과 출력

print("#" * 30)

# 텐서 뺄셈 연산
t5 = torch.sub(t1, t2)  # torch.sub를 사용한 뺄셈
t6 = t1 - t2  # 연산자 오버로딩을 통한 뺄셈
print(t5)  # 뺄셈 결과 출력
print(t6)  # 뺄셈 결과 출력

print("#" * 30)

# 텐서 곱셈 연산
t7 = torch.mul(t1, t2)  # torch.mul을 사용한 곱셈
t8 = t1 * t2  # 연산자 오버로딩을 통한 곱셈
print(t7)  # 곱셈 결과 출력
print(t8)  # 곱셈 결과 출력

print("#" * 30)

# 텐서 나눗셈 연산
t9 = torch.div(t1, t2)  # torch.div를 사용한 나눗셈
t10 = t1 / t2  # 연산자 오버로딩을 통한 나눗셈
print(t9)  # 나눗셈 결과 출력
print(t10)  # 나눗셈 결과 출력

# 기술적 사항
# 1. PyTorch에서는 다양한 방식으로 텐서 간의 기본 연산(덧셈, 뺄셈, 곱셈, 나눗셈)을 수행할 수 있다.
# 2. torch.add, torch.sub, torch.mul, torch.div와 같은 함수는 명시적인 연산을 제공하며, 연산자 오버로딩을 통해 간결하게 표현할 수 있다.

# 고찰
# 1. 텐서 연산은 딥러닝 모델의 기본적인 구성 요소이며, 연산의 효율성과 정확성을 위해 다양한 방법을 이해하고 활용하는 것이 중요하다.
# 2. 연산 방식에 따라 코드의 가독성이 달라질 수 있으므로, 상황에 맞는 방법을 선택하는 것이 중요하다.


tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
##############################
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


## g_tensor_operations_mm.py

In [23]:
import torch

# [핵심코드] 벡터의 내적 연산
t1 = torch.dot(
  torch.tensor([2, 3]), torch.tensor([2, 1])  # 두 벡터의 내적 계산
)
print(t1, t1.size())  # 결과 및 크기 출력

# [핵심코드] 행렬 곱셈 연산
t2 = torch.randn(2, 3)  # 2x3 크기의 랜덤 텐서 생성
t3 = torch.randn(3, 2)  # 3x2 크기의 랜덤 텐서 생성
t4 = torch.mm(t2, t3)  # 행렬 곱셈
print(t4, t4.size())  # 결과 및 크기 출력

# [핵심코드] 배치 행렬 곱셈 연산
t5 = torch.randn(10, 3, 4)  # 10개의 3x4 크기 배치 텐서 생성
t6 = torch.randn(10, 4, 5)  # 10개의 4x5 크기 배치 텐서 생성
t7 = torch.bmm(t5, t6)  # 배치 행렬 곱셈
print(t7.size())  # 결과 크기 출력

# 기술적 사항
# 1. torch.dot()은 두 벡터 간의 내적을 계산하는 함수이다.
# 2. torch.mm()은 두 행렬 간의 곱셈을 수행하며, torch.bmm()은 배치 행렬 곱셈을 수행한다.

# 고찰
# 1. 내적, 행렬 곱셈 및 배치 행렬 곱셈은 딥러닝 모델에서 중요한 연산으로, 이들 연산의 효율성을 이해하는 것이 중요하다.
# 2. PyTorch는 다양한 텐서 연산을 지원하여 복잡한 계산을 효율적으로 수행할 수 있게 해준다.


tensor(7) torch.Size([])
tensor([[1.6750, 2.2840],
        [0.0956, 1.0294]]) torch.Size([2, 2])
torch.Size([10, 3, 5])


## h_tensor_operations_matmul.py

In [26]:
import torch

# [핵심코드] 벡터 간의 내적: dot product
t1 = torch.randn(3)
t2 = torch.randn(3)
print(torch.matmul(t1, t2).size())  # 결과 크기: torch.Size([])

# [핵심코드] 행렬과 벡터 간의 연산: broadcasted dot
t3 = torch.randn(3, 4)
t4 = torch.randn(4)
print(torch.matmul(t3, t4).size())  # 결과 크기: torch.Size([3])

# [핵심코드] 배치된 행렬과 벡터 간의 연산: broadcasted dot
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(4)
print(torch.matmul(t5, t6).size())  # 결과 크기: torch.Size([10, 3])

# [핵심코드] 배치된 행렬 간의 연산: bmm
t7 = torch.randn(10, 3, 4)
t8 = torch.randn(10, 4, 5)
print(torch.matmul(t7, t8).size())  # 결과 크기: torch.Size([10, 3, 5])

# [핵심코드] 배치된 행렬과 행렬 간의 연산: bmm
t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4, 5)
print(torch.matmul(t9, t10).size())  # 결과 크기: torch.Size([10, 3, 5])

# 기술적 사항
# 1. torch.matmul()은 다양한 형태의 텐서 간의 곱셈을 지원하며, 브로드캐스팅 규칙을 따라 연산을 수행한다.
# 2. 벡터, 행렬, 그리고 배치 행렬 간의 연산을 통해 다양한 형태의 데이터 처리 가능.

# 고찰
# 1. 내적 및 행렬 곱셈은 데이터 과학 및 딥러닝에서 기본적인 연산으로, 이들을 이해하는 것이 중요하다.
# 2. PyTorch의 연산은 효율적인 메모리 사용과 성능 최적화를 통해 대규모 데이터 처리를 가능하게 한다.


torch.Size([])
torch.Size([3])
torch.Size([10, 3])
torch.Size([10, 3, 5])
torch.Size([10, 3, 5])


## i_tensor_boradcasting.py

In [29]:
import torch

# [핵심코드] 스칼라와 벡터의 곱
t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2)

print("#" * 50, 1)

# [핵심코드] 행렬과 벡터의 뺄셈
t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])
print(t3 - t4)

print("#" * 50, 2)

# [핵심코드] 행렬에 스칼라를 더하고 빼고 곱하고 나누기
t5 = torch.tensor([[1., 2.], [3., 4.]])
print(t5 + 2.0)  # t5.add(2.0)
print(t5 - 2.0)  # t5.sub(2.0)
print(t5 * 2.0)  # t5.mul(2.0)
print(t5 / 2.0)  # t5.div(2.0)

print("#" * 50, 3)

# [핵심코드] 정규화 함수
def normalize(x):
  return x / 255

t6 = torch.randn(3, 28, 28)
print(normalize(t6).size())

print("#" * 50, 4)

# [핵심코드] 다양한 텐서 간의 브로드캐스팅 연산
t7 = torch.tensor([[1, 2], [0, 3]])  # torch.Size([2, 2])
t8 = torch.tensor([[3, 1]])  # torch.Size([1, 2])
t9 = torch.tensor([[5], [2]])  # torch.Size([2, 1])
t10 = torch.tensor([7])  # torch.Size([1])
print(t7 + t8)   # >>> tensor([[4, 3], [3, 4]])
print(t7 + t9)   # >>> tensor([[6, 7], [2, 5]])
print(t8 + t9)   # >>> tensor([[8, 6], [5, 3]])
print(t7 + t10)  # >>> tensor([[ 8, 9], [ 7, 10]])

print("#" * 50, 5)

# [핵심코드] 브로드캐스팅을 이용한 텐서 연산
t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)  # 3rd & 2nd dims identical to t11, dim 0 absent
print(t12.shape)

t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1)  # 3rd dim = 1, 2nd dim is identical to t13
print(t14.shape)

t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)  # 3rd dim is identical to t15, 2nd dim is 1
print(t16.shape)

t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)  # 2nd dim is identical to t17, 3rd and 4th dims are 1
print((t17 + t18).size())

print("#" * 50, 6)

# [핵심코드] 브로드캐스팅을 이용한 텐서 연산
t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())  # torch.Size([5, 3, 4, 1])

t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())  # torch.Size([3, 1, 7])

t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())  # torch.Size([3, 3, 3])

# t25 = torch.empty(5, 2, 4, 1)
# t26 = torch.empty(3, 1, 1)
# print((t25 + t26).size())
# RuntimeError: The size of tensor a (2) must match
# the size of tensor b (3) at non-singleton dimension 1

print("#" * 50, 7)

# [핵심코드] 텐서의 원소 제곱
t27 = torch.ones(4) * 5
print(t27)  # >>> tensor([ 5, 5, 5, 5])

t28 = torch.pow(t27, 2)
print(t28)  # >>> tensor([ 25, 25, 25, 25])

# [핵심코드] 텐서의 원소 제곱
exp = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
a = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
t29 = torch.pow(a, exp)
print(t29)  # >>> tensor([   1.,    4.,   27.,  256.])
# 기술적 사항
# 1. PyTorch는 다양한 텐서 연산을 지원하며, 스칼라, 벡터, 행렬 간의 연산을 쉽게 수행할 수 있다.
# 2. 브로드캐스팅 기능을 통해 서로 다른 크기의 텐서 간의 연산을 가능하게 한다.
# 3. 다양한 텐서 조작 기능(예: add, sub, mul, div 등)을 제공하여 수학적 연산을 간편하게 처리할 수 있다.

# 고찰
# 1. 텐서 연산은 딥러닝 모델의 핵심 구성 요소로, 이러한 연산의 이해는 모델 개발 및 최적화에 매우 중요하다.
# 2. 브로드캐스팅은 메모리 효율성을 높이고 코드의 가독성을 향상시키는 중요한 기능이다.
# 3. PyTorch의 유연한 텐서 조작 기능을 활용하여 다양한 데이터 구조를 효과적으로 다룰 수 있다.

tensor([2., 4., 6.])
################################################## 1
tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])
################################################## 2
tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
################################################## 3
torch.Size([3, 28, 28])
################################################## 4
tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])
################################################## 5
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([5, 3, 4, 1])
################################################## 6
torch.Size([5, 3, 4, 1])
torch.Size([3, 1, 7])
torch.Size([3, 3, 3])
################################################## 7
tensor([5., 5., 5., 5.])
tensor([25., 25., 25., 25.])
tensor([  1

## j_tensor_indexing_slicing.py

In [32]:
import torch

# [핵심코드] 2D 텐서 생성
x = torch.tensor(
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9],
   [10, 11, 12, 13, 14]]
)

# [핵심코드] 텐서 인덱싱
print(x[1])  # >>> tensor([5, 6, 7, 8, 9])  # 1번째 행
print(x[:, 1])  # >>> tensor([1, 6, 11])  # 1번째 열
print(x[1, 2])  # >>> tensor(7)  # 1행 2열의 원소
print(x[:, -1])  # >>> tensor([4, 9, 14])  # 마지막 열

print("#" * 50, 1)

# [핵심코드] 슬라이싱
print(x[1:])  # >>> tensor([[ 5,  6,  7,  8,  9], [10, 11, 12, 13, 14]])  # 1행부터 끝까지
print(x[1:, 3:])  # >>> tensor([[ 8,  9], [13, 14]])  # 1행부터 끝까지, 3열부터 끝까지

print("#" * 50, 2)

# [핵심코드] 부분 텐서 생성 및 값 할당
y = torch.zeros((6, 6))  # 6x6 크기의 제로 텐서 생성
y[1:4, 2] = 1  # 특정 부분에 값 할당
print(y)

print(y[1:4, 1:4])  # >>> tensor([[0., 1., 1.], [0., 1., 1.], [0., 1., 1.]])

print("#" * 50, 3)

# [핵심코드] 2D 텐서 생성 및 인덱싱
z = torch.tensor(
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)
print(z[:2])  # >>> tensor([[1, 2, 3, 4], [2, 3, 4, 5]])  # 처음 두 행
print(z[1:, 1:3])  # >>> tensor([[3, 4], [6, 7]])  # 1행부터 끝까지, 1열부터 3열까지
print(z[:, 1:])  # >>> tensor([[2, 3, 4], [3, 4, 5], [6, 7, 8]])  # 모든 행, 1열부터 끝까지

# [핵심코드] 부분 텐서에 값 할당
z[1:, 1:3] = 0  # 특정 부분에 값 할당
print(z)  # >>> tensor([[1, 2, 3, 4], [2, 0, 0, 5], [5, 0, 0, 8]])

# 기술적 사항
# 1. PyTorch에서는 텐서의 인덱싱, 슬라이싱, 및 특정 부분에 값 할당을 통해 데이터를 쉽게 조작할 수 있다.
# 2. 텐서의 행과 열을 선택하거나 특정 부분을 변경하는 기능은 데이터 처리 및 전처리에서 매우 유용하다.

# 고찰
# 1. 텐서 인덱싱과 슬라이싱은 데이터 분석 및 딥러닝 모델 개발 시 핵심적인 기술이다.
# 2. 효율적인 데이터 조작을 통해 모델의 입력 데이터를 효과적으로 준비할 수 있다.


tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])
################################################## 1
tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])
################################################## 2
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])
################################################## 3
tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


## k_tensor_reshaping.py

In [35]:
import torch

# [핵심코드] 텐서 생성 및 모양 변경
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = t1.view(3, 2)  # Shape becomes (3, 2)
t3 = t1.reshape(1, 6)  # Shape becomes (1, 6)
print(t2)
print(t3)

# [핵심코드] 텐서 생성
t4 = torch.arange(8).view(2, 4)  # Shape becomes (2, 4)
t5 = torch.arange(6).view(2, 3)  # Shape becomes (2, 3)
print(t4)
print(t5)

print("#" * 50, 1)

# [핵심코드] 차원 축소
t6 = torch.tensor([[[1], [2], [3]]])  # Original tensor with shape (1, 3, 1)

t7 = t6.squeeze()  # Shape becomes (3,)  # 모든 차원에서 크기가 1인 차원 제거
t8 = t6.squeeze(0)  # Shape becomes (3, 1)  # 0번째 위치의 차원 제거
print(t7)
print(t8)

print("#" * 50, 2)

# [핵심코드] 차원 추가
t9 = torch.tensor([1, 2, 3])  # Original tensor with shape (3,)

t10 = t9.unsqueeze(1)  # Shape becomes (3, 1)  # 1번째 위치에 새로운 차원 추가
print(t10)

t11 = torch.tensor(
  [[1, 2, 3],
   [4, 5, 6]]
)
t12 = t11.unsqueeze(1)  # Shape becomes (2, 1, 3)  # 1번째 위치에 새로운 차원 추가
print(t12, t12.shape)

print("#" * 50, 3)

# [핵심코드] 텐서 평탄화
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])  # Original tensor with shape (2, 3)

t14 = t13.flatten()  # Shape becomes (6,)  # 텐서 평탄화
print(t14)

# Original tensor with shape (2, 2, 2)
t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])
t16 = torch.flatten(t15)  # 평탄화
t17 = torch.flatten(t15, start_dim=1)  # 첫 번째 차원부터 평탄화

print(t16)  # Shape becomes (8,)
print(t17)  # Shape becomes (2, 4)

print("#" * 50, 4)

# [핵심코드] 차원 순서 변경
t18 = torch.randn(2, 3, 5)
print(t18.shape)  # >>> torch.Size([2, 3, 5])
print(torch.permute(t18, (2, 0, 1)).size())  # >>> torch.Size([5, 2, 3])

# Original tensor with shape (2, 3)
t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# [핵심코드] 차원 순서 변경
t20 = torch.permute(t19, dims=(0, 1))  # Shape becomes (2, 3) still
t21 = torch.permute(t19, dims=(1, 0))  # Shape becomes (3, 2)
print(t20)
print(t21)

# [핵심코드] 텐서 전치
t22 = torch.transpose(t19, 0, 1)  # Shape becomes (3, 2)
print(t22)

t23 = torch.t(t19)  # Shape becomes (3, 2)
print(t23)

# 기술적 사항
# 1. PyTorch의 view()와 reshape() 함수는 텐서의 형태를 변경하는 데 사용된다.
# 2. squeeze()와 unsqueeze() 함수는 차원을 제거하거나 추가하는 데 사용된다.
# 3. flatten() 함수는 텐서를 평탄화하여 1차원으로 변환한다.
# 4. permute()와 transpose() 함수는 텐서의 차원 순서를 변경한다.

# 고찰
# 1. 텐서의 차원 조작은 딥러닝 모델에서 데이터 전처리 및 배치 처리에 매우 중요하다.
# 2. PyTorch의 다양한 텐서 조작 기능을 활용하여 복잡한 구조의 데이터를 효율적으로 다룰 수 있다.


tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])
################################################## 1
tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])
################################################## 2
tensor([[1],
        [2],
        [3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])
################################################## 3
tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
################################################## 4
torch.Size([2, 3, 5])
torch.Size([5, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


## l_tensor_concat.py

In [38]:
import torch

# [핵심코드] 다양한 크기의 텐서 생성
t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

# [핵심코드] 텐서 병합
t4 = torch.cat([t1, t2, t3], dim=1)
print(t4.shape)  # Shape 확인

print("#" * 50, 1)

# [핵심코드] 1D 텐서 생성 및 병합
t5 = torch.arange(0, 3)  # tensor([0, 1, 2])
t6 = torch.arange(3, 8)  # tensor([3, 4, 5, 6, 7])

t7 = torch.cat((t5, t6), dim=0)  # 병합
print(t7.shape)  # >>> torch.Size([8])
print(t7)  # >>> tensor([0, 1, 2, 3, 4, 5, 6, 7])

print("#" * 50, 2)

# [핵심코드] 2D 텐서 생성 및 병합
t8 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t9 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])

# 2차원 텐서간 병합
t10 = torch.cat((t8, t9), dim=0)  # 행 방향으로 병합
print(t10.size())  # >>> torch.Size([4, 3])
print(t10)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11]])

t11 = torch.cat((t8, t9), dim=1)  # 열 방향으로 병합
print(t11.size())  # >>> torch.Size([2, 6])
print(t11)
# >>> tensor([[ 0,  1,  2,  6,  7,  8],
#             [ 3,  4,  5,  9, 10, 11]])

print("#" * 50, 3)

# [핵심코드] 여러 2D 텐서 병합
t12 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t13 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])
t14 = torch.arange(12, 18).reshape(2, 3)  # torch.Size([2, 3])

t15 = torch.cat((t12, t13, t14), dim=0)  # 행 방향으로 병합
print(t15.size())  # >>> torch.Size([6, 3])
print(t15)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11],
#             [12, 13, 14],
#             [15, 16, 17]])

t16 = torch.cat((t12, t13, t14), dim=1)  # 열 방향으로 병합
print(t16.size())  # >>> torch.Size([2, 9])
print(t16)
# >>> tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
#             [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])

print("#" * 50, 4)

# [핵심코드] 3D 텐서 생성 및 병합
t17 = torch.arange(0, 6).reshape(1, 2, 3)  # torch.Size([1, 2, 3])
t18 = torch.arange(6, 12).reshape(1, 2, 3)  # torch.Size([1, 2, 3])

t19 = torch.cat((t17, t18), dim=0)  # 첫 번째 차원에서 병합
print(t19.size())  # >>> torch.Size([2, 2, 3])
print(t19)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5]],
#             [[ 6,  7,  8],
#              [ 9, 10, 11]]])

t20 = torch.cat((t17, t18), dim=1)  # 두 번째 차원에서 병합
print(t20.size())  # >>> torch.Size([1, 4, 3])
print(t20)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5],
#              [ 6,  7,  8],
#              [ 9, 10, 11]]])

t21 = torch.cat((t17, t18), dim=2)  # 세 번째 차원에서 병합
print(t21.size())  # >>> torch.Size([1, 2, 6])
print(t21)
# >>> tensor([[[ 0,  1,  2,  6,  7,  8],
#              [ 3,  4,  5,  9, 10, 11]]])

# 기술적 사항
# 1. torch.cat() 함수는 여러 텐서를 특정 차원에서 연결하는 데 사용된다.
# 2. 텐서를 병합할 때는 연결할 차원의 크기가 동일해야 한다.
# 3. 다양한 차원에서 텐서를 병합할 수 있어 유연한 데이터 구조를 생성할 수 있다.

# 고찰
# 1. 텐서 병합은 딥러닝 모델의 입력 데이터를 준비하는 데 필수적인 과정이다.
# 2. PyTorch의 텐서 조작 기능을 활용하여 복잡한 데이터 구조를 효과적으로 처리할 수 있다.


torch.Size([2, 6, 3])
################################################## 1
torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])
################################################## 2
torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])
################################################## 3
torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])
################################################## 4
torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
t

## m_tensor_stacking.py

In [41]:
import torch

# [핵심코드] 텐서 생성
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

# [핵심코드] 텐서 스택 및 연결
t3 = torch.stack([t1, t2], dim=0)  # 차원 0에서 스택
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)  # 차원 0에서 연결
print(t3.shape, t3.equal(t4))  # 모양 및 값 비교

# [핵심코드] 차원 1에서 스택 및 연결
t5 = torch.stack([t1, t2], dim=1)  # 차원 1에서 스택
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)  # 차원 1에서 연결
print(t5.shape, t5.equal(t6))  # 모양 및 값 비교

# [핵심코드] 차원 2에서 스택 및 연결
t7 = torch.stack([t1, t2], dim=2)  # 차원 2에서 스택
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)  # 차원 2에서 연결
print(t7.shape, t7.equal(t8))  # 모양 및 값 비교

print("#" * 50, 1)

# [핵심코드] 1D 텐서 생성
t9 = torch.arange(0, 3)  # tensor([0, 1, 2])
t10 = torch.arange(3, 6)  # tensor([3, 4, 5])

print(t9.size(), t10.size())  # 크기 출력
# >>> torch.Size([3]) torch.Size([3])

# [핵심코드] 1D 텐서 스택
t11 = torch.stack((t9, t10), dim=0)  # 차원 0에서 스택
print(t11.size())  # >>> torch.Size([2,3])
print(t11)
# >>> tensor([[0, 1, 2],
#             [3, 4, 5]])

# [핵심코드] 1D 텐서 연결
t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)  # 차원 0에서 연결
print(t11.equal(t12))  # 값 비교
# >>> True

# [핵심코드] 차원 1에서 스택
t13 = torch.stack((t9, t10), dim=1)  # 차원 1에서 스택
print(t13.size())  # >>> torch.Size([3,2])
print(t13)
# >>> tensor([[0, 3],
#             [1, 4],
#             [2, 5]])

# [핵심코드] 차원 1에서 연결
t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)  # 차원 1에서 연결
print(t13.equal(t14))  # 값 비교
# >>> True

# 기술적 사항
# 1. torch.stack() 함수는 여러 텐서를 새로운 차원에서 스택하여 하나의 텐서로 만든다.
# 2. torch.cat() 함수는 여러 텐서를 주어진 차원에서 연결한다.
# 3. 두 함수 모두 텐서를 다루는 데 유용하며, 데이터의 형태를 조정할 수 있다.

# 고찰
# 1. 텐서의 차원 조작은 딥러닝 모델에서 데이터 입력 형식을 설정하는 데 매우 중요하다.
# 2. PyTorch의 이러한 기능을 활용하여 다양한 형태의 데이터를 효과적으로 처리할 수 있다.


torch.Size([2, 2, 3]) True
torch.Size([2, 2, 3]) True
torch.Size([2, 3, 2]) True
################################################## 1
torch.Size([3]) torch.Size([3])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
True
torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
True


## n_tensor_vstack_hstack.py

In [44]:
import torch

# [핵심코드] 1D 텐서 생성 및 수직 스택
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.vstack((t1, t2))  # 수직으로 스택
print(t3)
# >>> tensor([[1, 2, 3],
#             [4, 5, 6]])

# [핵심코드] 2D 텐서 생성 및 수직 스택
t4 = torch.tensor([[1], [2], [3]])
t5 = torch.tensor([[4], [5], [6]])
t6 = torch.vstack((t4, t5))  # 수직으로 스택
# >>> tensor([[1],
#             [2],
#             [3],
#             [4],
#             [5],
#             [6]])

# [핵심코드] 3D 텐서 생성
t7 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)  # >>> (2, 2, 3)

t8 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t8.shape)  # >>> (2, 2, 3)

# [핵심코드] 3D 텐서 수직 스택
t9 = torch.vstack([t7, t8])  # 수직으로 스택
print(t9.shape)  # >>> (4, 2, 3)

print(t9)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6]],
#             [[ 7,  8,  9],
#              [10, 11, 12]],
#             [[13, 14, 15],
#              [16, 17, 18]],
#             [[19, 20, 21],
#              [22, 23, 24]]])

print("#" * 50, 1)

# [핵심코드] 1D 텐서 수평 스택
t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11))  # 수평으로 스택
print(t12)
# >>> tensor([1, 2, 3, 4, 5, 6])

# [핵심코드] 2D 텐서 수평 스택
t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])
t15 = torch.hstack((t13, t14))  # 수평으로 스택
print(t15)
# >>> tensor([[1, 4],
#             [2, 5],
#             [3, 6]])

# [핵심코드] 3D 텐서 생성
t16 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)  # >>> (2, 2, 3)

t17 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)  # >>> (2, 2, 3)

# [핵심코드] 3D 텐서 수평 스택
t18 = torch.hstack([t16, t17])  # 수평으로 스택
print(t18.shape)  # >>> (2, 4, 3)

print(t18)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6],
#              [13, 14, 15],
#              [16, 17, 18]],
#             [[ 7,  8,  9],
#              [10, 11, 12],
#              [19, 20, 21],
#              [22, 23, 24]]])

# 기술적 사항
# 1. torch.vstack() 함수는 텐서를 수직으로 스택하여 새로운 차원을 추가한다.
# 2. torch.hstack() 함수는 텐서를 수평으로 스택하여 새로운 차원을 추가한다.
# 3. 이 두 함수는 다차원 텐서를 다룰 때 유용하며, 데이터의 구조를 쉽게 변형할 수 있다.

# 고찰
# 1. 텐서의 스택 및 연결은 딥러닝 모델의 입력 데이터를 준비하는 데 중요한 과정이다.
# 2. PyTorch의 다양한 텐서 조작 기능을 활용하여 복잡한 데이터 구조를 효과적으로 처리할 수 있다.


tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])
################################################## 1
tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


[숙제 후기]

이번 학습을 통해 PyTorch의 텐서 조작에 대한 이해도를 높일 수 있었습니다. 특히, 텐서 생성, 변형, 병합 등 다양한 연산을 직접 실습하며 데이터 전처리에 필수적인 기술들을 익혔습니다.

텐서 조작의 중요성을 다시금 느꼈습니다. 모델에 입력되는 데이터의 형태가 잘못되면 모델 성능에 큰 영향을 미치기 때문에, 텐서 조작은 딥러닝 모델 개발에서 필수적인 과정입니다.

스택과 연결의 차이를 명확히 이해하게 되었습니다. torch.vstack()과 torch.hstack() 함수를 활용하여 텐서를 수직 또는 수평으로 병합하는 방법을 익히면서, 텐서의 차원을 자유롭게 조절할 수 있다는 점에 놀랐습니다.

브로드캐스팅과 차원 조작 역시 중요한 개념이었습니다. unsqueeze()와 squeeze() 함수를 통해 텐서의 차원을 추가하거나 제거하는 방법을 배우면서, 데이터를 모델에 맞게 변형하는 기술을 익혔습니다.

PyTorch의 유연성에 감탄했습니다. 다양한 텐서 연산을 지원하여 복잡한 데이터 구조도 쉽게 처리할 수 있다는 점이 PyTorch의 큰 장점이라고 생각합니다.

실습의 중요성을 다시 한번 확인했습니다. 이론적인 지식도 중요하지만, 실제로 코드를 작성하며 다양한 상황에 적용해 보는 것이 더욱 효과적이라는 것을 느꼈습니다.